config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :account, except: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank.rb
# frozen_string_literal: true

class Bank < ApplicationRecord; end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_one :account

  validates :name, presence: true
end

app/models/user/account.rb
class User::Account < ApplicationRecord
  belongs_to :user
  belongs_to :bank
end

app/controllers/accounts_controller.rb
# frozen_string_literal: true

#
# CRUD Account User
#
class AccountsController < ApplicationController
  before_action :account_form_setup, only: %i[edit update]

  def new
    build_account_form
  end

  def create
    build_account_form(account_form_params)

    if @account_form.save
      sign_in(User.find_by(name: @account_form.user_name))
      redirect_to account_path, notice: 'Account was created'
    else
      error_message = @account_form.errors.full_messages.join(',')
      redirect_to new_account_path, notice: error_message
    end
  end

  def show; end

  def edit; end

  def update
    return unless @account_form.update(account_form_params)

    redirect_to account_path, notice: 'Account was updated'
  end

  private

  def account_form_params
    params.require(:account_form).permit(
      :user_name,
      :user_phone_number,
      :account_type,
      :account_number
    )
  end

  def build_account_form(params = {})
    @account_form = AccountForm.new(params)
  end

  def account_form_setup
    @account_form = AccountForm.setup_by(current_user)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

#
# All controller must inherit from this class.
#
class ApplicationController < ActionController::Base
  include ApplicationHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

#
# Application Helper
#
module ApplicationHelper
  #
  # To create session of passed user
  #
  # @param [<object>] user current_user
  #
  #
  def sign_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/views/accounts/_form.html.erb
<%= form_with model: account_form, url: request_url, method: request_method, local: true do |f| %>
  <%= f.label 'Name' %>
  <%= f.text_field :user_name %>

  <%= f.label 'Phone Number' %>
  <%= f.text_field :user_phone_number %>

  <%= f.label 'Bank Type' %>
  <%= f.select :account_type, Bank.all.pluck(:name, :id) %>

  <%= f.label 'Bank Number' %>
  <%= f.text_field :account_number %>

  <%= f.submit 'Submit' %>
<% end %>

app/views/accounts/edit.html.erb
<%= render 'form', account_form: @account_form, request_url: account_path, request_method: :put %>

app/views/accounts/new.html.erb
<%= render 'form', {
      account_form: @account_form, request_url: account_path, request_method: :post
    } %>

app/views/accounts/show.html.erb
<h4>Information</h4>
<%= link_to 'Edit', edit_account_path %>

<table>
  <tr>
    <td>Name</td>
    <td><%= current_user.name %></td>
  </tr>

  <tr>
    <td>Phone Number</td>
    <td><%= current_user.phone_number %></td>
  </tr>

  <tr>
    <td>Bank</td>
    <td><%= current_user.account.bank.name %></td>
  </tr>

  <tr>
    <td>Account Number</td>
    <td><%= current_user.account.number %></td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExampleFormObject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/message' %>

    <%= yield %>
  </body>
</html>

app/views/shared/_message.html.erb
<% flash.each do |key, val| %>
  <%= val %>
<% end %>